### ISSUE TITLE
Screenshots doesn't get uploaded to TestRail

### ISSUE THREAD

**Issue by jshani** [zealous-tech/testrail-reporter#20]
When the tests dail the errors get added in testRail but screenshots are available locally but not in TestRail

**Comment by gevorg-vardanyan-im** [comment]
Hi @jshani, 
could you please provide some details ?

1. do you see any error in console related to screenshots uploading ?
2. are the tests that have a local screenshots available in TestRun ?
3. do you use existing TestRail Run or not ?

**Comment by gevorg-vardanyan-im** [comment]
Hi @jshani , we just released new version.
Could you please try with the new 1.0.15 version ?

And we also need some more details to troubleshoot the issue you have mentioned.
Could you also answer the questions above ?

Thanks in advance.

**Comment by arayik-chaparyan-im** [comment]
Hi @jshani 

As we haven’t received feedback from your side for two weeks, we are considering the issue resolved with the latest version and will close it as resolved.

Once again, thank you for taking the time to provide us with valuable insights in the form of bug reports with our module. Please continue using our module, and feel free to reach out to us if you encounter any further issues or have suggestions for improvement.

Your feedback is very valuable for us,
zealteam
